server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/uno_order?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  enabled: true
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  client:
    undo:
      log-table: undo_log

# RocketMQ 配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: uno-order-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 3
